spring:
  application:
    name: auth-saas-raes
  sql:
    init:
      mode: never

auth:
  jwt:
    access-token-ttl-seconds: 900
    ephemeral-keys: false
  platform:
    username: ${AUTH_PLATFORM_USERNAME:}
    password: ${AUTH_PLATFORM_PASSWORD:}

server:
  port: 8080
